DROP TABLE IF EXISTS `IAMS_SYS_DICT`;
CREATE TABLE `IAMS_SYS_DICT` (
  `SID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DICTID` int(11) NOT NULL COMMENT '字典ID',
  `CURRENT_TYPE` varchar(50) DEFAULT NULL COMMENT '当前类型代码',
  `CURRENT_TYPE_CNNAME` varchar(50) DEFAULT NULL COMMENT '当前类型中文',
  `DICT_CODE` varchar(50) DEFAULT NULL COMMENT '类型代码',
  `DICT_NAME` varchar(50) DEFAULT NULL COMMENT '显示文本',
  `SUB_TYPE` varchar(50) DEFAULT NULL COMMENT '子类型',
  `ORDER_INDEX` int(11) DEFAULT NULL COMMENT '排序号',
  `PARENTID` int(11) DEFAULT NULL COMMENT '上级',
  `IS_SHOW` tinyint(4) DEFAULT NULL COMMENT '是否显示',
  `IF_EDIT` tinyint(4) DEFAULT NULL COMMENT '是否可编辑',
  `CREATED_BY` varchar(32) DEFAULT NULL COMMENT '创建者',
  `CREATED_DT` datetime DEFAULT NULL COMMENT '创建时间',
  `VERSION` int(9) DEFAULT NULL COMMENT '版本号',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新者',
  `UPDATED_DT` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`SID`),
  UNIQUE KEY `SID_UNIQUE` (`SID`),
  UNIQUE KEY `DICTID_UNIQUE` (`DICTID`)
) ENGINE=InnoDB AUTO_INCREMENT=295 DEFAULT CHARSET=utf8 COMMENT='数据字典';

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (25, '04', '密级', '秘密', '秘密', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (26, '04', '密级', '机密', '机密', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (27, '04', '密级', '绝密', '绝密', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (28, '04', '密级', '内部', '内部', 'S', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (30, '04', '密级', '公开', '公开', 'S', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (31, '05', '保管期限', 'Y', '永久', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (32, '05', '保管期限', 'C', '长期', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (33, '05', '保管期限', 'D', '短期', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (34, '05', '保管期限', NULL, '10年', 'U', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (35, '05', '保管期限', 'C', '30年', 'U', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (183, '06', '文件类型', '1', '文字', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (184, '06', '文件类型', '2', '图纸', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (185, '06', '文件类型', '3', '底图', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (36, '08', '载体类型', NULL, '纸张', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (37, '08', '载体类型', NULL, '金石', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (38, '08', '载体类型', NULL, '甲骨', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (39, '08', '载体类型', NULL, '简牍', 'S', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (40, '08', '载体类型', NULL, '唱片', 'S', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (41, '08', '载体类型', NULL, '缣帛', 'S', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (42, '08', '载体类型', NULL, '胶卷', 'S', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (43, '08', '载体类型', NULL, '胶片', 'S', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (44, '08', '载体类型', NULL, '磁盘', 'S', 9, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (45, '08', '载体类型', NULL, '光盘', 'S', 10, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (46, '08', '载体类型', NULL, '磁带', 'S', 11, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (47, '09', '是否组卷', NULL, '未组卷', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (48, '09', '是否组卷', NULL, '已组卷', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (50, '10', '文种', NULL, '指示', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (51, '10', '文种', NULL, '通知', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (52, '10', '文种', NULL, '命令', 'S', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (53, '10', '文种', NULL, '报告', 'S', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (54, '10', '文种', NULL, '批复', 'S', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (55, '10', '文种', NULL, '会议纪要', 'S', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (56, '10', '文种', NULL, '函', 'S', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (57, '10', '文种', NULL, '协议书', 'S', 9, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (58, '10', '文种', NULL, '说明书', 'S', 10, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (59, '10', '文种', NULL, '鉴定书', 'S', 11, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (60, '10', '文种', NULL, '任务书', 'S', 12, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (61, '10', '文种', NULL, '判决书', 'S', 13, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (62, '10', '文种', NULL, '图书', 'S', 14, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (63, '10', '文种', NULL, '照会', 'S', 15, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (64, '10', '文种', NULL, '诰', 'S', 16, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (65, '10', '文种', NULL, '敕', 'S', 17, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (66, '10', '文种', NULL, '奏折', 'S', 18, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (29, '114', '结构类型', NULL, '砖混', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (159, '114', '结构类型', NULL, '框架', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (160, '114', '结构类型', NULL, '钢筋混凝土', 'U', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (161, '114', '结构类型', NULL, '钢筋混凝土剪力墙', 'U', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (186, '114', '结构类型', NULL, '简体', 'U', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (187, '114', '结构类型', NULL, '剪力墙', 'U', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (188, '114', '结构类型', NULL, '部分框支剪力墙', 'U', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (189, '114', '结构类型', NULL, '砌块结构', 'U', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (190, '114', '结构类型', '', '框剪', 'U', 9, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (193, '116', '照片色彩', '', '彩色', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (194, '116', '照片色彩', '', '黑白', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (195, '117', '照片正负片', '', '数码', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (196, '117', '照片正负片', '', '正片', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (197, '117', '照片正负片', '', '负片', 'U', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (198, '118', '流程处理状态', 'White', '初始', '0', 0, 0, '0', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (199, '118', '流程处理状态', 'White', '开始', '1', 1, 0, '0', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (200, '118', '流程处理状态', 'Red', '不通过', '900', 900, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (201, '118', '流程处理状态', 'BlueViolet', '再次提交', '800', 800, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (202, '118', '流程处理状态', 'White', '完成', '9', 9, 0, '0', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (203, '118', '流程处理状态', 'White', '已组卷', '100', 100, 0, '0', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (204, '118', '流程处理状态', 'YellowGreen', '已登记文件', '10', 10, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (205, '118', '流程处理状态', 'Green', '预验通过', '20', 20, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (91, '13', '性别', NULL, '男', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (92, '13', '性别', NULL, '女', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (93, '19', '单位', NULL, '册', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (94, '19', '单位', NULL, '米', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (95, '19', '单位', NULL, '页', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (96, '19', '单位', NULL, '盘', 'S', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (97, '19', '单位', NULL, '张', 'S', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (98, '19', '单位', NULL, '盒', 'S', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (99, '19', '单位', NULL, '卷', 'S', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (100, '20', '规格', NULL, '32开', 'S', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (101, '20', '规格', NULL, '8开', 'S', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (102, '20', '规格', NULL, '16开', 'S', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (103, '20', '规格', NULL, '4开', 'S', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (157, '20', '规格', '1', 'A4', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (158, '20', '规格', '2', 'A3', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (112, '24', '稿本', NULL, '草稿', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (113, '24', '稿本', NULL, '定槁', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (114, '24', '稿本', NULL, '手稿', 'U', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (115, '24', '稿本', NULL, '草图', 'U', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (116, '24', '稿本', NULL, '原图', 'U', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (117, '24', '稿本', NULL, '底图', 'U', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (118, '24', '稿本', NULL, '蓝图', 'U', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (119, '24', '稿本', NULL, '正本', 'U', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (120, '24', '稿本', NULL, '副本', 'U', 9, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (121, '24', '稿本', NULL, '原版', 'U', 10, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (122, '24', '稿本', NULL, '试行本', 'U', 11, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (123, '24', '稿本', NULL, '修订本', 'U', 12, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (124, '24', '稿本', NULL, '影印本', 'U', 13, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (125, '24', '稿本', NULL, '各种文字本', 'U', 14, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (224, 'ApproveResult', '审核结果', 'OK', '正确', NULL, 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (225, 'ApproveResult', '审核结果', 'NoFile', '缺页', NULL, 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (226, 'ApproveResult', '审核结果', 'CopyToOri', '复印件换原件', NULL, 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (206, 'Archive_Form', '工程类型', '1', '房屋建筑', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (207, 'Archive_Form', '工程类型', '2', '市政基础设施', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (229, 'Archive_Form', '工程类型', '3', '其它', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (208, 'Archive_Form_DEL', '工程类型', '3', '地下管线', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (21, 'BoxType', '案卷盒类型', '200', '2CM案卷盒', '5', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (22, 'BoxType', '案卷盒类型', '300', '3CM案卷盒', '5', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (227, 'BoxType', '案卷盒类型', '400', '4CM案卷盒', '5', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (228, 'BoxType', '案卷盒类型', '500', '5CM案卷盒', '5', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (12, 'CompanyType', '单位类型', 'ARCHIVE', '档案馆', '', 99, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (13, 'CompanyType', '单位类型', 'JSCompanyInfo', '建设单位', NULL, 10, 10, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (23, 'CompanyType', '单位类型', 'JLCompanyInfo', '监理单位', NULL, 30, 30, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (24, 'CompanyType', '单位类型', 'SGCompany', '施工单位', NULL, 20, 30, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (9, 'DefineType', '可定义类别', 'DH', '档号', NULL, 1, 1, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (10, 'DefineType', '可定义类别', 'WJM', '文件名', NULL, 2, 1, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (11, 'DefineType', '可定义类别', 'LJ', '路径', NULL, 3, 1, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (221, 'FileListTmpType', '归档目录类别', 'Text', '文字', NULL, 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (222, 'FileListTmpType', '归档目录类别', 'Picture', '图纸', NULL, 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (223, 'FileListTmpType', '归档目录类别', 'Photo', '照片', NULL, 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (214, 'FileTmpType', '文件分类', NULL, '文字', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (215, 'FileTmpType', '文件分类', NULL, '文字', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (216, 'FileTmpType', '文件分类', NULL, '文字', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (217, 'FileTmpType', '文件分类', NULL, '文字', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (218, 'FileTmpType', '文件分类', NULL, '图纸', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (219, 'FileTmpType', '文件分类', NULL, '照片', NULL, NULL, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (1, 'ModiaType', '介质类型', 'ZP', '照片', NULL, 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (2, 'ModiaType', '介质类型', 'LY', '录音', NULL, 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (3, 'ModiaType', '介质类型', 'LX', '录像', NULL, 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (6, 'ModiaType', '介质类型', NULL, '光盘', NULL, 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (8, 'ModiaType', '介质类型', NULL, '其它', NULL, 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (209, 'SignetType', '签章类别', 'JSCompanySignet', '建设单位章', 'JSCompanyInfo', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (210, 'SignetType', '签章类别', 'JLCompanySignet', '监理单位章', 'JLCompanyInfo', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (211, 'SignetType', '签章类别', 'SGCompanySignet', '施工单位章', 'SGCompany', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (212, 'SignetType', '签章类别', 'PMSignet', '项目经理章', 'JSCompanyInfo', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (220, 'SignetType', '签章类别', 'ARCHIVESignet', '档案中心章', 'ARCHIVE', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (4, 'SplitString', '分隔符', NULL, '-', NULL, 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (5, 'SplitString', '分隔符', NULL, '/', NULL, 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (16, 'WorkFlowDoStatus', '工作流状态', 'NoBegin', '未开始', '', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (17, 'WorkFlowDoStatus', '工作流状态', 'Beginning', '进行中', NULL, 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (18, 'WorkFlowDoStatus', '工作流状态', 'Finish', '已完成', NULL, 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (139, '电子文件类型', '电子文件格式类型', '', 'XML', 'U', 1, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (140, '电子文件类型', '电子文件格式类型', '', 'TIF', 'U', 2, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (141, '电子文件类型', '电子文件格式类型', '', 'MPEG', 'U', 3, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (142, '电子文件类型', '电子文件格式类型', '', 'WAV', 'U', 4, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (143, '电子文件类型', '电子文件格式类型', '', 'DWG', 'U', 5, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (144, '电子文件类型', '电子文件格式类型', '', 'MP3', 'U', 6, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (145, '电子文件类型', '电子文件格式类型', '', 'AVI', 'U', 7, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (146, '电子文件类型', '电子文件格式类型', '', 'JPEG', 'U', 8, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (147, '电子文件类型', '电子文件格式类型', '', 'RTF', 'U', 9, 0, '1', '1');

INSERT INTO IAMS_SYS_DICT(DICTID,CURRENT_TYPE,CURRENT_TYPE_CNNAME,DICT_CODE,DICT_NAME,SUB_TYPE,ORDER_INDEX,PARENTID,IS_SHOW,IF_EDIT)  VALUES (148, '电子文件类型', '电子文件格式类型', '', 'TXT', 'U', 10, 0, '1', '1');

COMMIT;