DROP TABLE IF EXISTS `IAMS_SYS_CONS_CATALOG`;
CREATE TABLE `IAMS_SYS_CONS_CATALOG` (
  `SID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CATALOGID` int(11) NOT NULL COMMENT '目录id',
  `CATALOGPID` int(11) DEFAULT NULL COMMENT '父级',
  `CONS_TYPE` int(11) DEFAULT NULL COMMENT '工程类别',
  `CONS_CODE` varchar(50) DEFAULT NULL COMMENT '工程资料代码',
  `CONS_NAME` varchar(100) DEFAULT NULL COMMENT '工程资料名称',
  `MATERIAL_NO` varchar(100) DEFAULT NULL COMMENT '施工技术资料编号',
  `MATERIAL_SOURCE` varchar(100) DEFAULT NULL COMMENT '工程资料来源',
  `ARC_COMPANY_TYPE` int(11) DEFAULT NULL COMMENT '归档单位类型',
  `ORDER_INDEX` int(11) DEFAULT NULL COMMENT '顺序号',
  `ISDIRECTORY` tinyint(1) DEFAULT NULL COMMENT '是否目录',
  `ARCHIVE_DIRECTORY_TYPE` int(11) DEFAULT NULL COMMENT '归档目录类别',
  `CREATED_BY` varchar(32) DEFAULT NULL COMMENT '创建者',
  `CREATED_DT` datetime DEFAULT NULL COMMENT '创建时间',
  `VERSION` int(9) DEFAULT NULL COMMENT '版本号',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新者',
  `UPDATED_DT` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`SID`),
  UNIQUE KEY `SID_UNIQUE` (`SID`),
  UNIQUE KEY `CATALOGID_UNIQUE` (`CATALOGID`)
) ENGINE=InnoDB AUTO_INCREMENT=413 DEFAULT CHARSET=utf8 COMMENT='建设档案归档目录信息表';

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (1, 0, 13, 'A', '工程准备阶段文件', 11, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (2, 1, 13, 'A01', '立项文件', 12, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (3, 2, 13, 'A0101', '项目建议书批复立件及项目建议书', 13, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (4, 2, 13, 'A0102', '可行性研究报告的批复文件及可行性研究报告', 14, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (5, 2, 13, 'A0103', '专家论证意见、项目评估文件', 15, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (6, 2, 13, 'A0104', '有关立项的会议纪要、领导批示', 16, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (10, 1, 13, 'A02', '建设用地、拆迁文件', 17, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (11, 10, 13, 'A0201', '选址申请及选址规划意见通知书', 18, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (12, 10, 13, 'A0202', '建设用地批准书', 19, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (13, 10, 13, 'A0203', '拆迁安置意见、协议、方案等', 20, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (14, 10, 13, 'A0204', '建设用地规划许可证及其附件', 21, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (15, 10, 13, 'A0205', '土地使用证明文件及其附件', 22, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (16, 10, 13, 'A0206', '建设用地钉桩通知单', 23, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (17, 1, 13, 'A03', '勘察、设计文件', 24, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (18, 17, 13, 'A0301', '工程地质勘察报告', 25, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (19, 17, 13, 'A0302', '水文地质勘察报告', 26, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (20, 17, 13, 'A0303', '初步设计文件（说明书）', 27, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (21, 17, 13, 'A0304', '设计方案审查意见', 28, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (22, 17, 13, 'A0305', '人防、环保、消防等有关主管部门（对设计方案）审查意见', 29, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (23, 17, 13, 'A0306', '设计计算书', 30, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (24, 17, 13, 'A0307', '施工图设计文件审查意见', 31, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (25, 17, 13, 'A0308', '节能设计备案文件', 32, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (27, 1, 13, 'A04', '招投标文件', 33, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (28, 27, 13, 'A0401', '勘察、设计招投标文件', 34, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (29, 27, 13, 'A0402', '勘察、设计合同', 35, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (30, 27, 13, 'A0403', '施工招投标文件', 36, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (31, 27, 13, 'A0404', '施工合同', 37, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (32, 27, 13, 'A0405', '工程监理招投标文件', 38, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (33, 27, 13, 'A0406', '监理合同', 39, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (36, 1, 13, 'A05', '开工审批文件', 40, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (37, 36, 13, 'A0501', '建设工程规划许可证及其附件', 41, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (38, 36, 13, 'A0502', '建设工程施工许可证', 42, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (45, 1, 13, 'A06', '工程造价文件', 43, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (46, 45, 13, 'A0601', '工程投资估算材料', 44, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (47, 45, 13, 'A0602', '工程设计概算材料', 45, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (48, 45, 13, 'A0603', '招标控制价格文件', 46, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (49, 1, 13, 'A07', '工程建设基本信息', 49, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (50, 0, 23, 'B', '监理文件（ B 类）', 61, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (51, 50, 23, 'B01', '监理管理文件', 62, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (52, 51, 23, 'B0101', '监理规划', 63, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (53, 51, 23, 'B0102', '监理实施细则', 64, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (54, 51, 23, 'B0103', '监理会议纪要', 65, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (55, 51, 23, 'B0104', '工作联系单', 66, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (56, 51, 23, 'B0105', '监理工程师通知', 67, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (57, 51, 23, 'B0106', '监理工程师通知回复单', 68, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (58, 51, 23, 'B0107', '工程暂停令', 69, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (59, 51, 23, 'B0108', '工程复工报审表', 70, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (63, 50, 23, 'B02', '进度控制文件', 71, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (64, 63, 23, 'B0201', '工程开工报审表', 72, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (65, 63, 23, 'B0202', '施工进度计划报审表', 73, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (66, 50, 23, 'B03', '质量控制文件', 74, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (67, 66, 23, 'B0301', '质量事故报告及处理资料', 75, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (68, 66, 23, 'B0302', '见证取样和送检人员备案表', 76, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (69, 66, 23, 'B0303', '见证记录', 77, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (72, 50, 23, 'B04', '造价控制文件', 78, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (73, 72, 23, 'B0401', '工程款支付', 79, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (74, 72, 23, 'B0402', '工程款支付证书', 80, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (75, 72, 23, 'B0403', '工程变更费用报审表', 81, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (76, 72, 23, 'B0404', '费用索赔申请表', 82, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (77, 72, 23, 'B0405', '费用索赔审批表', 83, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (78, 50, 23, 'B05', '工期管理文件', 84, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (79, 78, 23, 'B0501', '工程延期申请表', 85, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (80, 78, 23, 'B0502', '工程延期审批表', 86, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (83, 50, 23, 'B06', '监理验收文件', 87, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (84, 83, 23, 'B0601', '竣工移交证书', 88, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (85, 83, 23, 'B0602', '监理资料移交书', 89, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (92, 50, 23, 'B07', '其它资料', 90, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (93, 0, 24, 'C', '施工文件（C 类）', 91, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (94, 93, 24, 'C01', '施工管理文件', 92, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (95, 94, 24, 'C0101', '工程概况表', 93, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (96, 94, 24, 'C0102', '施工现场质量管理检查记录', 94, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (97, 94, 24, 'C0103', '分包单位资质报审表', 95, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (98, 94, 24, 'C0104', '建设单位质量事故勘查记录', 96, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (99, 94, 24, 'C0105', '建设工程质量事故报告书', 97, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (100, 94, 24, 'C0106', '见证试验检测汇总表', 98, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (106, 93, 24, 'C02', '施工技术文件', 99, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (107, 106, 24, 'C0201', '图纸会审记录', 100, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (108, 106, 24, 'C0202', '设计变更通知单', 101, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (109, 106, 24, 'C0203', '工程洽商记录（技术核定单）', 102, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (114, 93, 24, 'C03', '进度造价文件', 103, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (115, 114, 24, 'C0301', '工程开工报审表', 104, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (116, 114, 24, 'C0302', '工程复工报审表', 105, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (117, 114, 24, 'C0303', '工程延期申请表', 106, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (118, 114, 24, 'C0304', '工程款支付申请表', 107, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (119, 114, 24, 'C0305', '工程变更费用报审表', 108, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (120, 114, 24, 'C0306', '费用索赔申请表', 109, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (124, 93, 24, 'C04', '施工物资出厂质量证明及进场检测文件', 110, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (125, 124, 24, 'C0401', '出厂质量证明文件及检测报告', 111, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (126, 124, 24, 'C0402', '进场检验通用表格', 115, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (127, 124, 24, 'C0403', '进场复试报告', 117, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (156, 93, 24, 'C05', '施工记录文件', 140, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (157, 156, 24, 'C0501', '隐蔽工程验收记录', 141, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (158, 156, 24, 'C0502', '工程定位测量记录', 142, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (159, 156, 24, 'C0503', '基槽验线记录', 143, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (160, 156, 24, 'C0504', '建筑物垂直度、标高观测记录', 144, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (161, 156, 24, 'C0505', '沉降观测记录', 145, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (162, 156, 24, 'C0506', '地基验槽记录', 146, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (163, 156, 24, 'C0507', '地基钎探记录', 147, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (164, 156, 24, 'C0508', '大型构件吊装记录', 148, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (165, 156, 24, 'C0509', '地下工程防水效果检查记录', 149, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (166, 156, 24, 'C0510', '防水工程试水检查记录', 150, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (167, 156, 24, 'C0511', '通风（烟）道、垃圾道检查记录', 151, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (168, 156, 24, 'C0512', '预应力筋张拉记录', 152, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (169, 156, 24, 'C0513', '有粘结预应力结构灌浆记录', 153, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (170, 156, 24, 'C0514', '钢结构施工记录', 154, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (171, 156, 24, 'C0515', '网架（索膜）施工记录', 155, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (172, 156, 24, 'C0516', '木结构施工记录', 156, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (173, 156, 24, 'C0517', '幕墙注胶检查记录', 157, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (174, 156, 24, 'C0518', '自动扶梯、自动人行道的相邻区域检查记录', 158, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (175, 156, 24, 'C0519', '电梯电气装置安装检查记录', 159, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (176, 156, 24, 'C0520', '自动扶梯、自动人行道电气装置检查记录', 160, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (177, 156, 24, 'C0521', '自动扶梯、自动人行道整机安装质量检查记录', 161, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (189, 93, 24, 'C06', '施工试验记录及检测文件', 162, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (190, 189, 24, 'C0601', '通用表格', 163, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (191, 189, 24, 'C0602', '建筑与结构工程', 168, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (192, 189, 24, 'C0603', '给水排水及供暖工程', 206, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (193, 189, 24, 'C0604', '建筑电气工程', 216, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (194, 189, 24, 'C0605', '智能建筑工程', 226, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (195, 189, 24, 'C0606', '通风与空调工程', 232, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (196, 189, 24, 'C0607', '电梯工程', 242, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (279, 93, 24, 'C07', '施工质量验收文件', 252, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (280, 279, 24, 'C0701', '检验批质量验收记录', 253, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (281, 279, 24, 'C0702', '分项工程质量验收记录', 254, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (282, 279, 24, 'C0703', '分部（子分部）工程质量验收记录', 255, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (283, 279, 24, 'C0704', '建筑节能分部工程质量验收记录', 256, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (284, 279, 24, 'C0705', '自动喷水系统验收缺陷项目划分记录', 257, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (285, 279, 24, 'C0706', '程控电话交换系统分项工程质量验收记录', 258, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (286, 279, 24, 'C0707', '会议电视系统分项工程质量验收记录', 259, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (287, 279, 24, 'C0708', '卫星数字电视系统分项工程质量验收记录', 260, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (288, 279, 24, 'C0709', '有线电视系统分项工程质量验收记录', 261, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (289, 279, 24, 'C0710', '公共广播与紧急广播系统分项工程质量验收记录', 262, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (290, 279, 24, 'C0711', '计算机网络系统分项工程质量验收记录', 263, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (291, 279, 24, 'C0712', '应用软件系统分项工程质量验收记录', 264, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (292, 279, 24, 'C0713', '网络安全系统分项工程质量验收记录', 265, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (293, 279, 24, 'C0714', '空调与通风系统分项工程质量验收记录', 266, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (294, 279, 24, 'C0715', '变配电系统分项工程质量验收记录', 267, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (295, 279, 24, 'C0716', '公共照明系统分项工程质量验收记录', 268, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (296, 279, 24, 'C0717', '给水排水系统分项工程质量验收记录', 269, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (297, 279, 24, 'C0718', '热源和热交换系统分项工程质量验收记录', 270, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (298, 279, 24, 'C0719', '冷冻和冷却水系统分项工程质量验收记录', 271, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (299, 279, 24, 'C0720', '电梯和自动扶梯系统分项工程质量验收记录', 272, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (300, 279, 24, 'C0721', '数据通信接口分项工程质量验收记录', 273, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (301, 279, 24, 'C0722', '中央管理工作站及操作分站分项工程质量验收记录', 274, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (302, 279, 24, 'C0723', '系统实时性、可维护性、可靠性分项工程质量验收记录', 275, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (303, 279, 24, 'C0724', '现场设备安装及检测分项工程质量验收记录', 276, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (304, 279, 24, 'C0725', '火灾自动报警及消防联动系统分项工程质量验收记录', 277, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (305, 279, 24, 'C0726', '综合防范功能分项工程质量验收记录', 278, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (306, 279, 24, 'C0727', '视频安防监控系统分项工程质量验收记录', 279, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (307, 279, 24, 'C0728', '入侵报警系统分项工程质量验收记录', 280, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (308, 279, 24, 'C0729', '出入口控制（门禁）系统分项工程质量验收记录', 281, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (309, 279, 24, 'C0730', '巡更管理系统分项工程质量验收记录', 282, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (310, 279, 24, 'C0731', '停车场（库）管理系统分项工程质量验收记录', 283, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (311, 279, 24, 'C0732', '安全防范综合管理系统分项工程质量验收记录', 284, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (312, 279, 24, 'C0733', '综合布线系统安装分项工程质提验收记录', 285, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (313, 279, 24, 'C0734', '综合布线系统性能检测分项工程质量验收记录', 286, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (314, 279, 24, 'C0735', '系统集成网络连接分项工程质量验收记录', 287, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (315, 279, 24, 'C0736', '系统数据集成分项工程质量验收记录', 288, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (316, 279, 24, 'C0737', '系统集成综合管理及冗余功能分项工程质量验收记录', 289, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (317, 279, 24, 'C0738', '系统集成可维护性和安全性分项工程质量验收记录', 290, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (318, 279, 24, 'C0739', '电源系统分项工程质量验收记录', 291, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (320, 93, 24, 'C08', '施工验收文件', 292, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (321, 320, 24, 'C0801', '单位（子单位）工程竣工预验收报验表', 293, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (322, 320, 24, 'C0802', '单位（子单位）工程质量竣工验收记录', 294, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (323, 320, 24, 'C0803', '单位（于单位）工程质量控制资料核查记录', 295, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (324, 320, 24, 'C0804', '单位（子单位）工程安全和功能检验资料核查及主要功能抽查记录', 296, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (325, 320, 24, 'C0805', '单位（于单位）工程观感质量检查记录', 297, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (326, 320, 24, 'C0806', '施工资料移交书', 298, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (330, 93, 24, 'C09', '其他资料', 299, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (331, 0, 24, 'D', '竣工图（ D 类）', 300, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (332, 331, 24, 'D01', '建筑竣工图', 301, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (336, 331, 24, 'D02', '结构竣工图', 322, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (343, 331, 24, 'D03', '钢结构竣工图', 343, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (346, 331, 24, 'D04', '幕墙竣工图', 344, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (347, 0, 13, 'E', '工程竣工验收文件（ E 类）', 393, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (348, 347, 13, 'E01', '竣工验收与备案文件', 394, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (349, 348, 13, 'E0101', '勘察单位工程质量检查报告', 395, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (350, 348, 13, 'E0102', '设计单位工程质量检查报告', 396, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (351, 348, 13, 'E0103', '建设单位工程竣工总结', 397, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (352, 348, 13, 'E0104', '施工单位工程竣工总结', 398, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (353, 348, 13, 'E0105', '监理单位工程质量评估报告', 399, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (354, 348, 13, 'E0106', '工程竣工验收报告', 400, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (355, 348, 13, 'E0107', '工程竣工验收会议纪要', 401, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (356, 348, 13, 'E0108', '专家组竣工验收意见', 402, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (357, 347, 13, 'E02', '竣工决算文件', 411, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (358, 357, 13, 'E0201', '施工决算文件', 412, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (359, 357, 13, 'E0202', '监理决算文件', 413, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (360, 347, 13, 'E03', '工程声像资料等', 414, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (361, 360, 13, 'E0301', '开工前原貌、施工阶段、峻工新貌照片', 415, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (362, 360, 13, 'E0302', '工程建设过程的录音、录像资料（重大工程）', 416, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (365, 347, 13, 'E04', '其他工程文件', 417, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (368, 347, 13, 'E05', '其他资料', 418, '1', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (369, 0, 13, 'Y', '其他资料', 422, '0', NULL);

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (370, 45, 13, 'A0604', '合同价格文件', 47, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (371, 45, 13, 'A0605', '结算价格文件', 48, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (372, 49, 13, 'A0701', '工程概况信息表', 50, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (373, 49, 13, 'A0702', '建设单位法定代表人授权书', 51, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (374, 49, 13, 'A0703', '监理单位法定代表人授权书', 52, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (375, 49, 13, 'A0704', '施工单位法定代表人授权书', 53, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (376, 49, 13, 'A0705', '勘察单位法定代表人授权书', 54, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (377, 49, 13, 'A0706', '设计单位法定代表人授权书', 55, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (378, 49, 13, 'A0707', '建设单位项目负责人工程质量终身责任承诺书', 56, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (379, 49, 13, 'A0708', '监理单位总监理工程师工程质量终身责任承诺书', 57, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (380, 49, 13, 'A0709', '施工单位项目经理工程质量终身责任承诺书', 58, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (381, 49, 13, 'A0710', '勘察单位项目负责人工程质量终身责任承诺书', 59, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (382, 49, 13, 'A0711', '设计单位项目负责人工程质量终身责任承诺书', 60, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (383, 125, 24, 'C040101', '砂、石、砖、水泥、钢筋、隔热保温、防腐材料、轻骨料出 厂证明文件', 112, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (384, 125, 24, 'C040102', '主要设备、器具的安装使用说明书', 113, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (385, 125, 24, 'C040103', '涉及消防、安全、卫生、环保、节能的材料、设备的检测报告或法定机构出具的有效证明文件', 114, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (386, 126, 24, 'C040201', '设备及管道附件试验记录', 116, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (387, 127, 24, 'C040301', '钢材试验报告', 118, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (388, 127, 24, 'C040302', '水泥试验报告', 119, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (389, 127, 24, 'C040303', '砂试验报告', 120, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (390, 127, 24, 'C040304', '碎（卵）石试验报告', 121, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (391, 127, 24, 'C040305', '防水涂料试验报告', 122, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (392, 127, 24, 'C040306', '防水卷材试验报告', 123, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (393, 127, 24, 'C040307', '砖（砌块）试验报告', 124, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (394, 127, 24, 'C040308', '预应力筋复试报告', 125, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (395, 127, 24, 'C040309', '预应力锚具、夹具和连接器复试报告', 126, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (396, 127, 24, 'C040310', '装饰装修用门窗复试报告', 127, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (397, 127, 24, 'C040311', '装饰装修用人造木板复试报告', 128, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (398, 127, 24, 'C040312', '装饰装修用花岗石复试报告', 129, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (399, 127, 24, 'C040313', '装饰装修用安全玻璃复试报告', 130, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (400, 127, 24, 'C040314', '装饰装修用外墙面砖复试报告', 131, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (401, 127, 24, 'C040315', '钢结构用钢材复试报告', 132, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (402, 127, 24, 'C040316', '钢结构用防火涂料复试报告', 133, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (403, 127, 24, 'C040317', '钢结构用焊接材料复试报告', 134, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (404, 127, 24, 'C040318', '钢结构用高强度大六角头螺栓连接副复试报告', 135, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (405, 127, 24, 'C040319', '钢结构用扭剪型高强螺栓连接副复试报告', 136, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (406, 127, 24, 'C040320', '幕墙用铝塑板、石材、玻璃、结构胶复试报告', 137, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (407, 127, 24, 'C040321', '散热器、供暖系统保温材料、通风与空调工程绝热材料、风机盘管机组、低压配电系统电缆的见证取样复试报告', 138, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (408, 127, 24, 'C040322', '节能工程材料复试报告', 139, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (409, 190, 24, 'C060101', '设备单机试运转记录', 164, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (410, 190, 24, 'C060102', '系统试运转调试记录', 165, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (411, 190, 24, 'C060103', '接地电阻测试记录', 166, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (412, 190, 24, 'C060104', '绝缘电阻测试记录', 167, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (413, 191, 24, 'C060201', '锚杆试验报告', 169, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (414, 191, 24, 'C060202', '地基承载力检验报告', 170, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (415, 191, 24, 'C060203', '桩基检测报告', 171, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (416, 191, 24, 'C060204', '土工击实试验报告', 172, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (417, 191, 24, 'C060205', '回填土试验报告（应附图）', 173, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (418, 191, 24, 'C060206', '钢筋机械连接试验报告', 174, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (419, 191, 24, 'C060207', '钢筋焊接连接试验报告', 175, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (420, 191, 24, 'C060208', '砂浆抗压强度试验报告', 176, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (421, 191, 24, 'C060209', '砌筑砂浆试块强度统计、评定记录', 177, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (422, 191, 24, 'C060210', '混凝土配合比申请书、通知单', 178, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (423, 191, 24, 'C060211', '混凝土抗压强度试验报告', 179, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (424, 191, 24, 'C060212', '混凝土试块强度统计、评定记录', 180, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (425, 191, 24, 'C060213', '混凝土抗渗试验报告', 181, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (426, 191, 24, 'C060214', '砂、石、水泥放射性指标报告', 182, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (427, 191, 24, 'C060215', '混凝土碱总量计算书', 183, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (428, 191, 24, 'C060216', '外墙饰面砖样板粘结强度试验报告', 184, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (429, 191, 24, 'C060217', '后置埋件抗拔试验报告', 185, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (430, 191, 24, 'C060218', '超声波探伤报告、探伤记录', 186, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (431, 191, 24, 'C060219', '钢构件射线探伤报告', 187, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (432, 191, 24, 'C060220', '磁粉探伤报告', 188, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (433, 191, 24, 'C060221', '高强度螺栓抗滑移系数检测报告', 189, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (434, 191, 24, 'C060222', '钢结构焊接工艺评定', 190, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (435, 191, 24, 'C060223', '网架节点承载力试验报告', 191, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (436, 191, 24, 'C060224', '钢结构防腐、防火涂料厚度检测报告', 192, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (437, 191, 24, 'C060225', '木结构胶缝试验报告', 193, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (438, 191, 24, 'C060226', '木结构构件力学性能试验报告', 194, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (439, 191, 24, 'C060227', '木结构防护剂试验报告', 195, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (440, 191, 24, 'C060228', '幕墙双组分硅酮结构胶混匀性及拉断试验报告', 196, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (441, 191, 24, 'C060229', '幕墙的抗风压性能、空气渗透性能、雨水渗透性能及平面内变形性能检测报告', 197, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (442, 191, 24, 'C060230', '外门窗的抗风压性能、空气渗透性能和雨水渗透性能检测报告', 198, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (443, 191, 24, 'C060231', '墙体节能工程保温板材与基层粘结强度现场拉拔试验', 199, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (444, 191, 24, 'C060232', '外墙保温浆料同条件养护试件试验报告', 200, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (445, 191, 24, 'C060233', '结构实体混凝土强度验收记录', 201, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (446, 191, 24, 'C060234', '结构实体钢筋保护层厚度验收记录', 202, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (447, 191, 24, 'C060235', '围护结构现场实体检验', 203, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (448, 191, 24, 'C060236', '室内环境检测报告', 204, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (449, 191, 24, 'C060237', '节能性能检测报告', 205, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (450, 192, 24, 'C060301', '灌（满）水试验记录', 207, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (451, 192, 24, 'C060302', '强度严密性试验记录', 208, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (452, 192, 24, 'C060303', '通水试验记录', 209, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (453, 192, 24, 'C060304', '冲（吹）洗试验记录', 210, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (454, 192, 24, 'C060305', '通球试验记录', 211, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (455, 192, 24, 'C060306', '消火栓试射记录', 212, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (456, 192, 24, 'C060307', '钢炉试运行记录', 213, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (457, 192, 24, 'C060308', '安全阀定压合格证书', 214, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (458, 192, 24, 'C060309', '自动喷水灭火系统联动试验记录', 215, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (459, 193, 24, 'C060401', '电气接地装置平面示意图表', 217, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (460, 193, 24, 'C060402', '电气器具通电安全检查记录', 218, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (461, 193, 24, 'C060403', '电气设备空载试运行记录', 219, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (462, 193, 24, 'C060404', '建筑物照明通电试运行记录', 220, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (463, 193, 24, 'C060405', '大型照明灯具承载试验记录', 221, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (464, 193, 24, 'C060406', '漏电开关模拟试验记录', 222, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (465, 193, 24, 'C060407', '大容量电气线路结点测温记录', 223, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (466, 193, 24, 'C060408', '低压配电电源质量测试记录', 224, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (467, 193, 24, 'C060409', '建筑物照明系统照度测试记录', 225, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (468, 194, 24, 'C060501', '综合布线测试记录', 227, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (469, 194, 24, 'C060502', '光纤损耗测试记录', 228, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (470, 194, 24, 'C060503', '视频系统末端测试记录', 229, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (471, 194, 24, 'C060504', '子系统检测记录', 230, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (472, 194, 24, 'C060505', '系统试运行记录', 231, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (473, 195, 24, 'C060601', '风管漏光检测记录', 233, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (474, 195, 24, 'C060602', '风管漏风检测记录', 234, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (475, 195, 24, 'C060603', '各房间室内风量测量记录', 235, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (476, 195, 24, 'C060604', '管网风量平衡记录', 236, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (477, 195, 24, 'C060605', '空调系统试运转调试记录', 237, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (478, 195, 24, 'C060606', '空调水系统试运转调试记录', 238, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (479, 195, 24, 'C060607', '制冷系统气密性试验记录', 239, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (480, 195, 24, 'C060608', '净化空调系统检测记录', 240, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (481, 195, 24, 'C060609', '防排烟系统联合试运行记录', 241, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (482, 196, 24, 'C060701', '轿厢平层准确度测量记录', 243, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (483, 196, 24, 'C060702', '电梯层门安全装置检测记录', 244, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (484, 196, 24, 'C060703', '电梯电气安全装置检测记录', 245, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (485, 196, 24, 'C060704', '电梯整机功能检测记录', 246, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (486, 196, 24, 'C060705', '电梯主要功能检测记录', 247, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (487, 196, 24, 'C060706', '电梯负荷运行试验记录', 248, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (488, 196, 24, 'C060707', '电梯负荷运行试验曲线图表', 249, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (489, 196, 24, 'C060708', '自动扶梯、自动人行道安全装置检测记录', 250, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (490, 196, 24, 'C060709', '自动抉梯、自动人行道整机性能、运行试验记录', 251, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (491, 331, 24, 'D05', '建筑给水排水及供暖竣工图', 345, '1', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (492, 331, 24, 'D06', '建筑电气竣工图', 366, '1', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (493, 331, 24, 'D07', '室内装饰竣工图', 387, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (494, 331, 24, 'D08', '智能建筑竣工图', 388, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (495, 331, 24, 'D09', '通风与空调竣工图', 389, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (496, 331, 24, 'D10', '室外工程竣工图', 390, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (497, 331, 24, 'D11', '规划红线内的室外给水、排水、供热、供电、照明管线等竣工图', 391, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (498, 331, 24, 'D12', '规划红线内的道路、园林绿化、喷灌设施等竣工图', 392, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (499, 332, 24, 'D0101', '建筑竣工图一', 302, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (500, 332, 24, 'D0102', '建筑竣工图二', 303, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (501, 332, 24, 'D0103', '建筑竣工图三', 304, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (502, 332, 24, 'D0104', '建筑竣工图四', 305, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (503, 332, 24, 'D0105', '建筑竣工图五', 306, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (504, 332, 24, 'D0106', '建筑竣工图六', 307, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (505, 332, 24, 'D0107', '建筑竣工图七', 308, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (506, 332, 24, 'D0108', '建筑竣工图八', 309, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (507, 332, 24, 'D0109', '建筑竣工图九', 310, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (508, 332, 24, 'D0110', '建筑竣工图十', 311, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (509, 332, 24, 'D0111', '建筑竣工图十一', 312, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (510, 332, 24, 'D0112', '建筑竣工图十二', 313, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (511, 332, 24, 'D0113', '建筑竣工图十三', 314, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (512, 332, 24, 'D0114', '建筑竣工图十四', 315, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (513, 332, 24, 'D0115', '建筑竣工图十五', 316, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (514, 332, 24, 'D0116', '建筑竣工图十六', 317, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (515, 332, 24, 'D0117', '建筑竣工图十七', 318, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (516, 332, 24, 'D0118', '建筑竣工图十八', 319, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (517, 332, 24, 'D0119', '建筑竣工图十九', 320, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (518, 332, 24, 'D0120', '建筑竣工图二十', 321, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (519, 336, 24, 'D0201', '结构竣工图一', 323, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (520, 336, 24, 'D0202', '结构竣工图二', 324, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (521, 336, 24, 'D0203', '结构竣工图三', 325, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (522, 336, 24, 'D0204', '结构竣工图四', 326, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (523, 336, 24, 'D0205', '结构竣工图五', 327, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (524, 336, 24, 'D0206', '结构竣工图六', 328, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (525, 336, 24, 'D0207', '结构竣工图七', 329, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (526, 336, 24, 'D0208', '结构竣工图八', 330, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (527, 336, 24, 'D0209', '结构竣工图九', 331, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (528, 336, 24, 'D0210', '结构竣工图十', 332, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (529, 336, 24, 'D0211', '结构竣工图十一', 333, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (530, 336, 24, 'D0212', '结构竣工图十二', 334, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (531, 336, 24, 'D0213', '结构竣工图十三', 335, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (532, 336, 24, 'D0214', '结构竣工图十四', 336, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (533, 336, 24, 'D0215', '结构竣工图十五', 337, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (534, 336, 24, 'D0216', '结构竣工图十六', 338, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (535, 336, 24, 'D0217', '结构竣工图十七', 339, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (536, 336, 24, 'D0218', '结构竣工图十八', 340, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (537, 336, 24, 'D0219', '结构竣工图十九', 341, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (538, 336, 24, 'D0220', '结构竣工图二十', 342, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (539, 491, 24, 'D0501', '建筑给水排水竣工图一', 346, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (540, 491, 24, 'D0502', '建筑给水排水竣工图二', 347, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (541, 491, 24, 'D0503', '建筑给水排水竣工图三', 348, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (542, 491, 24, 'D0504', '建筑给水排水竣工图四', 349, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (543, 491, 24, 'D0505', '建筑给水排水竣工图五', 350, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (544, 491, 24, 'D0506', '建筑给水排水竣工图六', 351, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (545, 491, 24, 'D0507', '建筑给水排水竣工图七', 352, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (546, 491, 24, 'D0508', '建筑给水排水竣工图八', 353, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (547, 491, 24, 'D0509', '建筑给水排水竣工图九', 354, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (548, 491, 24, 'D0510', '建筑给水排水竣工图十', 355, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (549, 491, 24, 'D0511', '建筑给水排水竣工图十一', 356, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (550, 491, 24, 'D0512', '建筑给水排水竣工图十二', 357, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (551, 491, 24, 'D0513', '建筑给水排水竣工图十三', 358, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (552, 491, 24, 'D0514', '建筑给水排水竣工图十四', 359, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (553, 491, 24, 'D0515', '建筑给水排水竣工图十五', 360, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (554, 491, 24, 'D0516', '建筑给水排水竣工图十六', 361, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (555, 491, 24, 'D0517', '建筑给水排水竣工图十七', 362, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (556, 491, 24, 'D0518', '建筑给水排水竣工图十八', 363, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (557, 491, 24, 'D0519', '建筑给水排水竣工图十九', 364, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (558, 491, 24, 'D0520', '建筑给水排水竣工图二十', 365, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (559, 492, 24, 'D0601', '建筑电气竣工图一', 367, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (560, 492, 24, 'D0602', '建筑电气竣工图二', 368, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (561, 492, 24, 'D0603', '建筑电气竣工图三', 369, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (562, 492, 24, 'D0604', '建筑电气竣工图四', 370, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (563, 492, 24, 'D0605', '建筑电气竣工图五', 371, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (564, 492, 24, 'D0606', '建筑电气竣工图六', 372, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (565, 492, 24, 'D0607', '建筑电气竣工图七', 373, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (566, 492, 24, 'D0608', '建筑电气竣工图八', 374, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (567, 492, 24, 'D0609', '建筑电气竣工图九', 375, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (568, 492, 24, 'D0610', '建筑电气竣工图十', 376, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (569, 492, 24, 'D0611', '建筑电气竣工图十一', 377, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (570, 492, 24, 'D0612', '建筑电气竣工图十二', 378, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (571, 492, 24, 'D0613', '建筑电气竣工图十三', 379, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (572, 492, 24, 'D0614', '建筑电气竣工图十四', 380, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (573, 492, 24, 'D0615', '建筑电气竣工图十五', 381, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (574, 492, 24, 'D0616', '建筑电气竣工图十六', 382, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (575, 492, 24, 'D0617', '建筑电气竣工图十七', 383, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (576, 492, 24, 'D0618', '建筑电气竣工图十八', 384, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (577, 492, 24, 'D0619', '建筑电气竣工图十九', 385, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (578, 492, 24, 'D0620', '建筑电气竣工图二十', 386, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (579, 348, 13, 'E0109', '工程竣工验收证书', 403, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (580, 348, 13, 'E0110', '防蚁验收报告', 404, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (581, 348, 13, 'E0111', '规划、消防、环保、民防、防雷等部门出具的认可文件或准许使用文件', 405, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (582, 348, 13, 'E0112', '房屋建筑工程质量保修书', 406, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (583, 348, 13, 'E0113', '住宅质量保证书、住宅使用说明书', 407, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (584, 348, 13, 'E0114', '建设工程竣工验收备案表', 408, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (585, 348, 13, 'E0115', '建设工程档案预验收意见', 409, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (586, 348, 13, 'E0116', '城市建设档案移交书', 410, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (587, 347, 13, 'E06', '房地产开发项目竣工综合验收备案证', 419, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (588, 347, 13, 'E07', '管线点成果表', 420, '0', '221');

INSERT INTO IAMS_SYS_CONS_CATALOG(CATALOGID,CATALOGPID,ARC_COMPANY_TYPE,CONS_CODE,CONS_NAME,ORDER_INDEX,ISDIRECTORY,ARCHIVE_DIRECTORY_TYPE)  VALUES (589, 347, 13, 'E08', '管线竣工图', 421, '0', '221');

COMMIT;