CREATE TABLE IAMS_PRO_ORGAN
(
  `ORG_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `ORG_NO` varchar(50) DEFAULT NULL COMMENT '机构编码',
  `ORG_CODE` varchar(50) DEFAULT NULL COMMENT '组织机构代码',
  `ORG_NAME` varchar(200) DEFAULT NULL COMMENT '机构名称',
  `ORG_DESC` varchar(500) DEFAULT NULL COMMENT '机构备注',
  `ORG_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `ORG_PHONE` varchar(50) DEFAULT NULL COMMENT '联系电话',
  `ORG_CONTACTS` varchar(50) DEFAULT NULL COMMENT '联系人',
  `ORG_CONT_MOBILE` varchar(50) DEFAULT NULL COMMENT '联系人电话',
  `ORG_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `ORG_STATUS` int(1) DEFAULT NULL COMMENT '状态',
  `ORG_TYPE` varchar(50) DEFAULT NULL COMMENT '机构类别',
  `ORG_EMAIL` varchar(100) DEFAULT NULL COMMENT 'EMAIL',
  `ORG_ADDR` varchar(500) DEFAULT NULL COMMENT '机构地址',
  `CREATRE_ORG_ID` varchar(50) DEFAULT NULL COMMENT '创建的组织ID',
  `OUTER_ID` varchar(100) DEFAULT NULL COMMENT '外链接数据的ID',
  `OUTER_TYPE` varchar(100) DEFAULT NULL COMMENT '外链接的类型'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='组织机构表';

CREATE TABLE IAMS_PRO_USER
(
  `USER_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `USER_ORG_ID` varchar(32) DEFAULT NULL COMMENT '机构代码',
  `USER_TYPE` varchar(32) DEFAULT NULL COMMENT '用户类别',
  `USER_ACCOUNT` varchar(32) DEFAULT NULL COMMENT '登陆账号',
  `USER_PSW` varchar(50) DEFAULT NULL COMMENT '登陆账号',
  `USER_USERNAME` varchar(32) DEFAULT NULL COMMENT '用户名称',
  `USER_PHONE` varchar(32) DEFAULT NULL COMMENT '个人电话',
  `USER_MOBILE` varchar(32) DEFAULT NULL COMMENT '手机号码',
  `USER_FAX` varchar(32) DEFAULT NULL COMMENT '传真号',
  `USER_WXNO` varchar(32) DEFAULT NULL COMMENT '微信号',
  `USER_WXBINDING` varchar(10) DEFAULT NULL COMMENT '微信绑定状态',
  `USER_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `USER_STATUS` int(1) DEFAULT NULL COMMENT '状态',
  `USER_DESC` varchar(500) DEFAULT NULL COMMENT '备注',
  `CREATRE_ORG_ID` varchar(50) DEFAULT NULL COMMENT '创建的组织ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';

CREATE TABLE IAMS_PRO_ROLE
(
  `ROLE_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `ROLE_NAME` varchar(200) DEFAULT NULL COMMENT '角色名称',
  `ROLE_USE_ORG_ID` varchar(500) DEFAULT NULL COMMENT '使用组织机构ID',
  `ROLE_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `ROLE_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `ROLE_STATUS` int(1) DEFAULT NULL COMMENT '状态',
  `ROLE_TYPE` varchar(50) DEFAULT NULL COMMENT '角色类别',
  `ROLE_DESC` varchar(500) DEFAULT NULL COMMENT '角色备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表';

CREATE TABLE IAMS_PRO_ROLE_PRIV(
  `ROPR_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `ROLE_SID` int(15) NOT NULL COMMENT '角色主键',
  `ROPR_OBJ_TYPE` varchar(50) DEFAULT NULL COMMENT '权限类型 文件夹:folder',
  `ROPR_OBJ_ID` varchar(200) DEFAULT NULL COMMENT '权限ID',
  `ROPR_OPERATION_ID` varchar(200) DEFAULT NULL COMMENT '操作ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色权限表';

CREATE TABLE IAMS_PRO_USER_ROLE(
  `USRO_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `USER_SID` int(15) NOT NULL COMMENT '用户ID',
  `ROLE_SID` int(15) NOT NULL COMMENT '角色主键',
  `USRO_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `USRO_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户角色表';

CREATE TABLE IAMS_PRO_DICTIONARY(
  `DICT_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `DICT_VALUE` varchar(200) NOT NULL COMMENT '字典值',
  `DICT_TEXT` varchar(200) DEFAULT NULL COMMENT '字典文字',
  `DICT_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `DICT_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `DICT_PARENT_ID` int(15) DEFAULT NULL COMMENT '父级ID',
  `DICT_PARENT_IDLIST` varchar(200) DEFAULT NULL COMMENT '父级列表',
  `DICT_STATUS` int(1) DEFAULT 1 COMMENT '状态',
  `DICT_IS_SELECTED` int(1) DEFAULT 0 COMMENT '默认选中',
  `DICT_DESC` varchar(500) DEFAULT NULL COMMENT '字典备注',
  `DICT_CHILD_COUNT` int(3) DEFAULT 0 COMMENT '子节点数量',
  `DICT_EX_ATTR1` varchar(200) DEFAULT NULL COMMENT '扩展值1',
  `DICT_EX_ATTR2` varchar(200) DEFAULT NULL COMMENT '扩展值2',
  `DICT_EX_ATTR3` varchar(200) DEFAULT NULL COMMENT '扩展值3',
  `DICT_EX_ATTR4` varchar(200) DEFAULT NULL COMMENT '扩展值4'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据字典表';

CREATE TABLE IAMS_PRO_OP_LOG(
  `LOG_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `LOG_TYPE` varchar(50) DEFAULT NULL COMMENT '日志类型',
  `LOG_NAME` varchar(50) DEFAULT NULL COMMENT '日志名称',
  `LOG_TEXT` text DEFAULT NULL COMMENT '日志内容',
  `USER_SID` int(15) DEFAULT NULL COMMENT '相关人员',
  `LOG_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LOG_DESC` varchar(500) DEFAULT NULL COMMENT '字典备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='操作日志表';

CREATE TABLE IAMS_PRO_ENG_CONF_TYPE
(
  `ENG_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `ENG_VALUE` varchar(50) DEFAULT NULL COMMENT '工程类别值',
  `ENG_NAME` varchar(50) DEFAULT NULL COMMENT '工程类别名',
  `ENG_DESC` varchar(500) DEFAULT NULL COMMENT '工程类别备注',
  `ENG_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `ENG_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `ENG_STATUS` int(1) DEFAULT NULL COMMENT '状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工程类别表';


CREATE TABLE IAMS_PRO_ENG_CONF_MATE(
  `MATE_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `ENG_SID` int(15) NOT NULL COMMENT '工程类别表ID',
  `ENG_VALUE` varchar(50) DEFAULT NULL COMMENT '工程类别值',
  `MATE_VALUE` varchar(150) DEFAULT NULL COMMENT '资料类别值(工程资料代码)',
  `MATE_NAME` varchar(150) DEFAULT NULL COMMENT '资料类别名称',
  `UNIT_TYPE` varchar(250) DEFAULT NULL COMMENT '归档单位类型',
  `MATE_NEED` int(1) DEFAULT 0 COMMENT '是否必须',
  `MATE_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `MATE_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `MATE_STATUS` int(1) DEFAULT NULL COMMENT '状态',
  `MATE_DESC` varchar(500) DEFAULT NULL COMMENT '资料类别备注',
  `MATE_TYPE` varchar(500) DEFAULT NULL COMMENT '资料类型(归档目录类别: 文字/图纸/照片)',
  `MATE_P_SID` int(15) NOT NULL PRIMARY KEY COMMENT '父ID',
  `MATERIAL_NO` varchar(100) NOT NULL PRIMARY KEY COMMENT '施工技术资料编号',
  `ISDIRECTORY` int(1) NOT NULL PRIMARY KEY COMMENT '是否目录',
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工程类别资料设置表';

CREATE TABLE IAMS_PRO_FILE(
  `FILE_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `FILE_NAME` varchar(500) NOT NULL COMMENT '文件名称',
  `FILE_STORE_NAME` varchar(500) NOT NULL COMMENT '文件存储名称',
  `FILE_STORE_PATH` varchar(2000) NOT NULL COMMENT '文件存储路径',
  `FILE_ORDER` int(15) NOT NULL COMMENT '文件序号',
  `FILE_TYPE` varchar(20) DEFAULT NULL COMMENT '文件类别',
  `FILE_SIZE` varchar(50) DEFAULT NULL COMMENT '文件大小',
  `FILE_CREATER` varchar(20) DEFAULT NULL COMMENT '上传人',
  `FILE_CREATE_TIME` datetime DEFAULT NULL COMMENT '上传时间',
  `FILE_EXTENSION` varchar(20) DEFAULT NULL COMMENT '扩展名',
  `FILE_UNIT_ID` varchar(20) DEFAULT NULL COMMENT '上传单位ID',
  `FILE_UNIT_NAME` varchar(50) DEFAULT NULL COMMENT '上传单位名称',
  `FILE_DESC` varchar(500) DEFAULT NULL COMMENT '文件备注',
  `FILE_GROUP1` varchar(50) DEFAULT NULL COMMENT '文件分组1',
  `FILE_GROUP2` varchar(50) DEFAULT NULL COMMENT '文件分组2',
  `OUTER_TABLE_NAME` varchar(50) DEFAULT NULL COMMENT '外键主记录表',
  `OUTER_SID` varchar(50) DEFAULT NULL COMMENT '外键主记录ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文件存储表';


CREATE TABLE IAMS_PRO_OUTER_ORGAN
(
  `OORG_SID` int(15) NOT NULL PRIMARY KEY COMMENT '主键',
  `OORG_NAME_CN` varchar(200) DEFAULT NULL COMMENT '公司名称（中文）',
  `OORG_NAME_EN` varchar(200) DEFAULT NULL COMMENT '公司名称（英文）',
  `OORG_TYPE` varchar(50) DEFAULT NULL COMMENT '公司类型',
  `OORG_CODE` varchar(100) DEFAULT NULL COMMENT '组织机构代码',
  `OORG_AREA` varchar(200) DEFAULT NULL COMMENT '所属区域',
  `OORG_POSTAL_CODE` varchar(50) DEFAULT NULL COMMENT '邮政编码',
  `OORG_ADDR` varchar(250) DEFAULT NULL COMMENT '单位地址（经营地址）',
  `OORG_LEGAL_NAME` varchar(50) DEFAULT NULL COMMENT '法人姓名',
  `OORG_LEGAL_IDCARD` varchar(50) DEFAULT NULL COMMENT '身份证号',
  `OORG_CONTACTS` varchar(50) DEFAULT NULL COMMENT '联系人',
  `OORG_CONT_MOBILE` varchar(50) DEFAULT NULL COMMENT '联系人手机',
  `OORG_PHONE` varchar(50) DEFAULT NULL COMMENT '联系电话',
  `OORG_EMAIL` varchar(100) DEFAULT NULL COMMENT 'EMAIL',
  `OORG_FAX` varchar(50) DEFAULT NULL COMMENT '传真',
  `OORG_INTRODUCTION` varchar(1500) DEFAULT NULL COMMENT '公司简介',
  `OORG_DESC` varchar(500) DEFAULT NULL COMMENT '机构备注',
  `OORG_CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OORG_ACCOUNT` varchar(50) DEFAULT NULL COMMENT '登录账号',
  `OORG_PSW` varchar(50) DEFAULT NULL COMMENT '密码',
  `OORG_ORDER` int(15) DEFAULT NULL COMMENT '排序号',
  `OORG_STATUS` int(1) DEFAULT NULL COMMENT '状态',
  `OORG_ORGNA_ID` varchar(50) DEFAULT NULL COMMENT '创建组织ID',
  `OORG_ORGNA_TYPE` varchar(50) DEFAULT NULL COMMENT '创建组织类型',
  `OORG_CREATERID` varchar(50) DEFAULT NULL COMMENT '创建人ID',
  `OORG_CREATER` varchar(50) DEFAULT NULL COMMENT '创建人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='外部组织机构表';

CREATE TABLE IAMS_PRO_ADVISORY(
  `ADV_SID` varchar(50) NOT NULL PRIMARY KEY COMMENT '主键',
  `ADV_CONTENT` varchar(2000) DEFAULT NULL COMMENT '咨询内容',
  `USER_ID` varchar(50) DEFAULT NULL COMMENT '咨询人ID',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '咨询人姓名',
  `ORGAN_ID` varchar(50) DEFAULT NULL COMMENT '咨询单位ID',
  `ORGAN_NAME` varchar(50) DEFAULT NULL COMMENT '咨询单位名称',
  `CREATETIME` datetime DEFAULT NULL COMMENT '创建时间',
  `STATUS` varchar(50) DEFAULT NULL COMMENT '状态',
  `OUTER_ID` varchar(50) DEFAULT NULL COMMENT '关联的外键ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='咨询表';

CREATE TABLE IAMS_PRO_ADVISORY_REPLY(
  `REPLY_SID` varchar(50) NOT NULL PRIMARY KEY COMMENT '主键',
  `REPLY_CONTENT` varchar(2000) DEFAULT NULL COMMENT '回复内容',
  `ADV_SID` varchar(50) DEFAULT NULL COMMENT '咨询ID',
  `USER_ID` varchar(50) DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '用户姓名',
  `ORGAN_ID` varchar(50) DEFAULT NULL COMMENT '单位ID',
  `ORGAN_NAME` varchar(50) DEFAULT NULL COMMENT '单位名称',
  `CREATETIME` datetime DEFAULT NULL COMMENT '创建时间',
  `STATUS` varchar(50) DEFAULT NULL COMMENT '状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='答复表';

CREATE TABLE IAMS_PRO_MAP_OBJ(
  `ID` varchar(50) NOT NULL PRIMARY KEY COMMENT '主键',
  `LAT` varchar(50) DEFAULT NULL COMMENT '坐标LAT',
  `LNG` varchar(50) DEFAULT NULL COMMENT '坐标LNG',
  `BINDTO` varchar(50) DEFAULT NULL COMMENT '绑定到对象',
  `BINDTOID` varchar(50) DEFAULT NULL COMMENT '绑定到对象ID',
  `TYPE` varchar(50) DEFAULT NULL COMMENT '类型',
  `PATH` varchar(2000) DEFAULT NULL COMMENT '路径',
  `DISTEXT` varchar(200) DEFAULT NULL COMMENT '文本'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='地图对象表';