insert into IAMS_PRO_DICTIONARY(DICT_SID,DICT_VALUE,DICT_TEXT,DICT_ORDER,DICT_CREATE_TIME,DICT_PARENT_ID,DICT_PARENT_IDLIST,DICT_STATUS,DICT_IS_SELECTED,DICT_DESC,
                                DICT_CHILD_COUNT)
VALUES(0,'RootValue','根字典',1,'2018-05-10',null,'0',1,'0','',0);


insert into iams_pro_user(USER_SID,USER_ORG_ID,USER_TYPE,USER_ACCOUNT,USER_PSW,USER_USERNAME)
values(0,0,'超级管理员','manager','c4ca4238a0b923820dcc509a6f75849b','超级管理员');

insert into iams_pro_organ(ORG_SID,ORG_NO,ORG_CODE,ORG_NAME,ORG_CREATE_TIME,ORG_ORDER,ORG_STATUS,ORG_TYPE)
    VALUES (0,0,0,'管理组织','2018-05-18',0,1,'管理组织');