CREATE TABLE TB4D_DEMO
(
    DEMO_ID        NVARCHAR(100)       NOT NULL PRIMARY KEY,
    IS_VIRTUAL      INT DEFAULT '0' NOT NULL,
    ORDER_NUM       INT             NOT NULL,
    STATUS          INT             NOT NULL,
    NAME_TEXT      NVARCHAR(100) NULL,
    F_DATE DATETIME NULL
)
GO

CREATE TABLE TB4D_ORGAN
(
    ORGAN_ID        NVARCHAR(100)       NOT NULL PRIMARY KEY,
    CHILD_COUNT     INT        DEFAULT NULL,
    IS_VIRTUAL      INT DEFAULT '0' NOT NULL,
    ORDER_NUM       INT             NOT NULL,
    ORGAN_ADDRESS   NVARCHAR(300)  DEFAULT NULL,
    ORGAN_CONTACTOR NVARCHAR(100)  DEFAULT NULL,
    ORGAN_DOMAIN    NVARCHAR(300)       NOT NULL,
    ORGAN_FAX       NVARCHAR(100)  DEFAULT NULL,
    ORGAN_NAME      NVARCHAR(300)       NOT NULL,
    ORGAN_NUM       NVARCHAR(200)  DEFAULT NULL,
    ORGAN_PHONE     NVARCHAR(100)  DEFAULT NULL,
    ORGAN_POST      NVARCHAR(20)   DEFAULT NULL,
    ORGAN_TYPE      NVARCHAR(50)   DEFAULT NULL,
    PARENT_ID       NVARCHAR(100)  DEFAULT NULL,
    PARENT_ID_LIST  NVARCHAR(1200) DEFAULT NULL,
    SHORT_NAME      NVARCHAR(150)  DEFAULT NULL,
    ORGAN_STATUS          INT             NOT NULL
)
GO
